name: Scrape for new codes

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno cache --lock=deno.lock ./scrapers/deps.ts

      - name: Scraping...
        run: chmod +x .github/workflows/scrape_all.sh && .github/workflows/scrape_all.sh

      - name: Merge output files
        run: awk '!seen[$0]++' codes-genshin.txt GI-Fandom-results.txt GI-hashblen-results.txt > codes-genshin.txt

      - name: Push changes
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
          GIT_TRACE_PACKET: 1
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          REPO: ${{github.repository}}
        run: chmod +x .github/workflows/commit.sh && .github/workflows/commit.sh
