name: Scrape for new codes

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno cache --lock=deno.lock ./scrapers/deps.ts

      - name: Scraping...
        run: chmod +x .github/workflows/scrape_all.sh && .github/workflows/scrape_all.sh

      - name: Push changes
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          REPO: ${{github.repository}}
        run: chmod +x .github/workflows/commit.sh && .github/workflows/commit.sh
